# Telephone Numbers project Docker-compose file

version: '3.8'

volumes:
    postgres_data:
    redis_data:

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    #command: gunicorn series.wsgi:application --config ./gunicorn.conf.py
    env_file:
      - ./telephone_numbers/env/docker.env
    volumes:
      - .:/code
    ports:
      - 8000:8000
#    expose:
#      - 8000
    depends_on:
      - db
     # - redis
#      - celery
#      - celery-beat

  db:
      image: postgres:13-alpine
      restart: always
      env_file:
        - ./telephone_numbers/env/postgres_docker.env
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - target: 5432
          published: 5433
          protocol: tcp
          mode: host


  redis:
    image: redis:6.0.9-alpine3.12
    command: redis-server
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

