version: '3.8'

volumes:
    postgres_data:
    redis_data:

services:
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn telephone_numbers.wsgi:application --config ./gunicorn.conf.py
    env_file:
      - ./telephone_numbers/env/docker.env
    volumes:
      - .:/code
#    ports:
#      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - celery
      - celery-beat
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web
    restart: always

  db:
      image: postgres:13-alpine
      restart: always
      env_file:
        - ./telephone_numbers/env/postgres_docker.env
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - target: 5432
          published: 5433
          protocol: tcp
          mode: host
      command: -c track_commit_timestamp=on

  redis:
    image: redis:6.0.9-alpine3.12
    command: redis-server
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

  celery:
    build: .
    command: celery -A telephone_numbers worker --loglevel=INFO -E
    env_file:
      - ./telephone_numbers/env/docker.env
    restart: always
    environment:
      - C_FORCE_ROOT=1
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    hostname: celery-main

  celery-beat:
    build: .
    command: celery -A telephone_numbers  beat --loglevel=INFO --pidfile=
    env_file:
      - ./telephone_numbers/env/docker.env
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    hostname: celery-beat

  flower:
    image: mher/flower:0.9.5
    env_file:
      - ./telephone_numbers/env/flower.env
    depends_on:
      - redis
      - celery
      - celery-beat
    restart: always
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host


