# Generated by Django 3.1.3 on 2020-11-07 07:54

import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneNumbersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_or_def', models.PositiveSmallIntegerField(validators=[django.core.validators.RegexValidator(re.compile('^[\\d]{3}$'), 'Поле "abc_or_def" должно быть 3х значным интегром', 'abc_or_def_length')], verbose_name='АВС/DEF')),
                ('numbers_range', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Диапазон номеров без АВС/DEF.')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Емкость диапазона номеров')),
                ('operator', models.CharField(max_length=50, verbose_name='Наименование оператора связи')),
                ('region', models.CharField(max_length=100, verbose_name='Местоположение оператора связи')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления данных')),
            ],
            options={
                'verbose_name': 'Диапазон телефонных номеров',
                'verbose_name_plural': 'Диапазоны телефонных номеров',
                'required_db_vendor': 'postgresql',
                'unique_together': {('abc_or_def', 'numbers_range')},
            },
        ),
    ]
