# Generated by Django 3.1.3 on 2020-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascertain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonenumbersmodel',
            name='operator',
            field=models.CharField(max_length=150, verbose_name='Наименование оператора связи'),
        ),
        migrations.AlterField(
            model_name='telephonenumbersmodel',
            name='volume',
            field=models.PositiveIntegerField(verbose_name='Емкость диапазона номеров'),
        ),
    ]
