# Generated by Django 3.1.3 on 2020-11-08 10:27

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascertain', '0002_auto_20201107_1929'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AlterField(
            model_name='telephonenumbersmodel',
            name='abc_or_def',
            field=models.PositiveSmallIntegerField(verbose_name='АВС/DEF'),
        ),
        migrations.AlterUniqueTogether(
            name='telephonenumbersmodel',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='telephonenumbersmodel',
            index=django.contrib.postgres.indexes.GistIndex(fields=['abc_or_def', 'numbers_range'], fillfactor=100, name='ascertain_t_abc_or__f3800c_gist'),
        ),
    ]
