# Generated by Django 3.1.3 on 2020-11-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascertain', '0003_auto_20201108_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephonenumbersmodel',
            name='update_date',
        ),
    ]
